export const CART_ACTION_TYPES = {
  SET_CART_ITEMS: 'SET_CART_ITEMS',
  SET_OPEN_CART: 'SET_OPEN_CART',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  DECREMENT_ITEM_COUNT: 'DECREMENT_ITEM_COUNT',
};
